### ISSUE TITLE
contact for fosdem Q&A about pararules

### ISSUE THREAD

**Issue by pietroppeter** [paranim/pararules#4]
a bit of unorthodox way of contacting but maybe you see better github notifications than mail.
Will you be able to join the Live Q&A for you talk at Fosdem?
You should join this link with a matrix account and we should test audio and video before the Q&A starts, which is in about 1 hour!

https://chat.fosdem.org/#/room/#nim-nim_pararules:fosdem.org

**Comment by oakes** [comment]
Trying to join the room but it says "You are not invited to this room."

**Comment by pietroppeter** [comment]
whooo you are here! let me know your username!
